export default {
  name: 'tripBrief',
  title: 'Trip Brief',
  type: 'document',
  fields: [
    { name: 'title', title: 'Title', type: 'string' },
    { name: 'clientName', title: 'Client Name', type: 'string' },
    { name: 'tripType', title: 'Trip Type', type: 'string' },
    { name: 'originCity', title: 'Origin City', type: 'string' },
    { name: 'tripLengthDays', title: 'Trip Length Days', type: 'number' },
    { name: 'travellerCount', title: 'Traveller Count', type: 'number' },
    { name: 'budgetBand', title: 'Budget Band', type: 'string' },
    { name: 'preferredClimate', title: 'Preferred Climate', type: 'array', of: [{ type: 'string' }] },
    { name: 'travelStyle', title: 'Travel Style', type: 'array', of: [{ type: 'string' }] },
    { name: 'desiredExperiences', title: 'Desired Experiences', type: 'array', of: [{ type: 'string' }] },
    { name: 'mustAvoid', title: 'Must Avoid', type: 'array', of: [{ type: 'string' }] },
    { name: 'notes', title: 'Notes', type: 'text' },
    { name: 'autoSummary', title: 'Auto Summary', type: 'text' },
    { name: 'createdAt', title: 'Created At', type: 'datetime' },
  ],
}